### ISSUE TITLE
로컬 시각화

### ISSUE THREAD

**Issue by holenet** [heatz123/Reinforcement-Learning-Gomoku#1]
learn.py에서 Pygame을 이용하여 시각화

**Comment by holenet** [comment]
필요할까?

**Comment by heatz123** [comment]
어차피 웹클라이언트가 있으니까 그걸로 시각화하는 게 나을 것 같긴 함. (굳이 웹클라, 파이게임 2개 만들 필요는 없을 듯)
로컬에서 테스트하려 하면 print()와 input() 써서 간단하게만 하는 걸로 합시다
